### ISSUE TITLE
Google docs conversion docs are incomplete?

### ISSUE THREAD

**Issue by abhinuvpitale** [salesforce/metro#1]
I am not sure if its complete. I am still unsure where to mention the files I wish to convert? Should they be in my Google Drive? Or should they be coupled with the zip file that gets downloaded.

I guess the documentation can be made more explicit with a better example.

**Comment by antorcol** [comment]
Yes. Make sure the docs you want to convert are available. You create a google sheet listing the pages. Let me check to see whether I added the example sheet.

**Comment by antorcol** [comment]
Yes. If you check out the docs for GoogleDoc work available from (https://metro.readthedocs.io/en/latest/using/convert-google-doc.html), it has you create a Google Slides doc in a convenient location, and then provide URLs to the Google docs or folders you want converted in that sheet.

The ReadTheDocs are linked from the main Readme.md in this repo.
